2024-Shinhan-Hackathon-ForeignKey/soltravel

- backend/build.gradle
- backend/src/main/java/com/ssafy/soltravel/BackendApplication.java
- backend/src/main/java/com/ssafy/soltravel/common/Header.java
- backend/src/main/java/com/ssafy/soltravel/config/ModelMapperConfig.java
- backend/src/main/java/com/ssafy/soltravel/config/SecurityConfig.java
- backend/src/main/java/com/ssafy/soltravel/config/WebClientConfig.java
- backend/src/main/java/com/ssafy/soltravel/controller/AccountController.java
- backend/src/main/java/com/ssafy/soltravel/domain/Currency.java
- backend/src/main/java/com/ssafy/soltravel/domain/Exchange.java
- backend/src/main/java/com/ssafy/soltravel/domain/ForeignAccount.java
- backend/src/main/java/com/ssafy/soltravel/domain/GeneralAccount.java
- backend/src/main/java/com/ssafy/soltravel/dto/ResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account/response/CreateAccountResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account/response/DeleteAccountResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/currency/CurrencyDto.java
- backend/src/main/java/com/ssafy/soltravel/handler/GlobalExceptionHandler.java
- backend/src/main/java/com/ssafy/soltravel/repository/GeneralAccountRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/util/LogUtil.java
- backend/src/main/resources/application-dev.yml
- backend/src/main/resources/application.yml
- 계좌 생성, 삭제 API 구현
- 로깅 유틸 생성
- 전역 예외 처리 핸들러 구현
- Mapper, WebClient Config 빈 설정 추가
어떤 변경 사항이 있나요?
> [BE] Feat: 계좌 생성, 삭제 구현

- backend/src/main/java/com/ssafy/soltravel/BackendApplication.java
- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/domain/ExchangeRate.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/repository/ExchangeRateRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/resources/application.yml
> [BE] Merge: be/feat/exchange into master

- backend/build.gradle
- backend/src/main/java/com/ssafy/soltravel/config/RedisConfig.java
- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/domain/ExchangeRate.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateRegisterRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/resources/application.yml
- 환율 타입 에러 수정했습니다.
- Redis 설정 추가했습니다.
어떤 변경 사항이 있나요?
> [BE] Merge: be/feat/exchange -> master

- backend/build.gradle
- backend/src/main/java/com/ssafy/soltravel/config/QueryDSLConfig.java
- backend/src/main/java/com/ssafy/soltravel/config/WebClientConfig.java
- backend/src/main/java/com/ssafy/soltravel/controller/UserController.java
- backend/src/main/java/com/ssafy/soltravel/domain/User.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/UserCreateRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/UserSearchRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/UserSearchResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/api/UserCreateRequestBody.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/api/UserSearchRequestBody.java
- backend/src/main/java/com/ssafy/soltravel/exception/UserNotFoundException.java
- backend/src/main/java/com/ssafy/soltravel/filter/JwtAutheticationFilter.java
- backend/src/main/java/com/ssafy/soltravel/repository/UserRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/user/UserService.java
회원가입 구현(/user/join)
회원조회 구현
- 단건 조회(/search/{userId})
- 전체 조회(/search/all)
- 검색 가능(QueryDSL)
회원 API 관련 DTO 추가
어떤 변경 사항이 있나요?
> [BE] Feat: QueryDSL을 활용한 유저 조회 기능과 회원 가입 API 구현

- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/domain/Enum/CurrencyType.java
- backend/src/main/java/com/ssafy/soltravel/domain/Enum/OrderByType.java
- backend/src/main/java/com/ssafy/soltravel/domain/Enum/Role.java
- backend/src/main/java/com/ssafy/soltravel/domain/Enum/TransacntionType.java
- backend/src/main/java/com/ssafy/soltravel/domain/GeneralAccount.java
- backend/src/main/java/com/ssafy/soltravel/domain/User.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/TransactionHistoryDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/TransactionHistoryRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/TransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/TransferRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/response/DepositResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/response/TransferHistoryResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/UserDetailDto.java
- backend/src/main/java/com/ssafy/soltravel/mapper/AccountMapper.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- 계좌 입금, 출금, 이체. 거래내역 조회 구현
어떤 변경 사항이 있나요?
> [BE] Feat: Account 거래 관련 기능 구현

- backend/src/main/java/com/ssafy/soltravel/controller/NotificationController.java
- backend/src/main/java/com/ssafy/soltravel/dto/NotificationDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/AccountInfoDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/repository/ParticipantRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/NotificationService.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- 자동 환전시 모임원 알림 구현
어떤 변경 사항이 있나요?
> [BE] Merge: 환전 실행 및 알림 구현

- backend/src/main/java/com/ssafy/soltravel/controller/AccountController.java
- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/domain/redis/PreferenceRate.java
- backend/src/main/java/com/ssafy/soltravel/dto/NotificationDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/Account.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/AccountInfoDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/repository/GeneralAccountRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/NotificationService.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- 외화 계좌 입금 및 조회 구현
어떤 변경 사항이 있나요?
> [BE] Feat: 외화 계좌 입금 구현

- backend/src/main/java/com/ssafy/soltravel/controller/AccountController.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/util/SecurityUtil.java
- userId 추출 시큐리티 유틸 생성
- 외화 계좌 해지 (구현중)
어떤 변경 사항이 있나요?
> [BE] Feat: 외화 계좌 해지 (구현중)

- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/AccountInfoDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/ForeignTransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- 원화 -> 달러 환전시 금액 계산하는 로직 구현
어떤 변경 사항이 있나요?
> [BE] Merge: 원화 -> 달러 환전 금액 계산 구현

- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- TransactionService에 SecurityUtil 적용
어떤 변경 사항이 있나요?
> [BE] Merge: TransactionService에 SecurityUtil 적용

- backend/build.gradle
- backend/src/main/java/com/ssafy/soltravel/controller/AuthController.java
- backend/src/main/java/com/ssafy/soltravel/controller/UserController.java
- backend/src/main/java/com/ssafy/soltravel/handler/GlobalExceptionHandler.java
Swagger 적용
- AuthController
- UserController 
GlobalExceptionHandler
- 인증 코드 불일치시 응답 HttpStatusCode 변경 (401 -> 400)
어떤 변경 사항이 있나요?
> [BE] Feat: Swagger 적용(1차)

- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/AccountInfoDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeCurrencyDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateRegisterRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/TransactionHistoryDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/ForeignTransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/TransactionHistoryRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/response/DepositResponseDto.java
- ExchangeController에 Swagger 적용
- TransactionController의 외화 계좌부분 Swagger 적용
어떤 변경 사항이 있나요?
> [BE] Merge: ExchangeController에 Swagger 적용

- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/controller/NotificationController.java
- backend/src/main/java/com/ssafy/soltravel/exception/InvalidAmountException.java
- backend/src/main/java/com/ssafy/soltravel/service/NotificationService.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- 환전API Swagger 수정
- 알림API Swagger적용
어떤 변경 사항이 있나요?
> [BE] Feat: 환전API Swagger 수정 및 알림API Swagger적용

- backend/src/main/java/com/ssafy/soltravel/config/ApiKeyConfig.java
api-key.txt 저장 위치 변경
resources -> root
어떤 변경 사항이 있나요?
> [BE] Build: api-key.txt 위치 변경

- frontend/soltravel/src/App.tsx
- frontend/soltravel/src/components/common/Footer.tsx
- frontend/soltravel/src/pages/MainPage.tsx
- frontend/soltravel/src/pages/user/SignUp.tsx
- 메인페이지 트래블월렛 수정
- 하단 nav바 회화를 전체로 수정
- 메인페이지 환율 세로선 추가
- 메인페이지 navigate 연결
어떤 변경 사항이 있나요?
> [FE] Design: 메인페이지, 하단 nav바 디자인 및 navigate 연결

- backend/src/main/java/com/ssafy/soltravel/dto/account/AccountDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account/response/DeleteAccountResponseDto.java
- Account관련 반환 타입 변경
어떤 변경 사항이 있나요?
> [BE] Merge: Account관련 반환 타입 변경

- frontend/soltravel/src/redux/accountSlice.ts
- frontend/soltravel/src/redux/store.tsx
- Provider 설정
- store 설정
- slice 설정
어떤 변경 사항이 있나요?
> [FE] Feat: Redux 환경설정 및 보안 키보드 모달 구현

- frontend/soltravel/src/App.tsx
- frontend/soltravel/src/components/user/UpdateUserForm.tsx
- frontend/soltravel/src/components/user/UserForm.tsx
- frontend/soltravel/src/index.tsx
- frontend/soltravel/src/pages/user/MyPage.tsx
- frontend/soltravel/src/pages/user/SignUp.tsx
- frontend/soltravel/src/pages/user/UserUpdate.tsx
- frontend/soltravel/src/redux/accountSlice.ts
- frontend/soltravel/src/redux/store.tsx
- 마이페이지 정보 수정 버튼 추가
- 마이페이지 배경색 수정
- 회원가입 페이지 비밀번호 확인 추가
- 회원정보 수정 페이지 디자인
어떤 변경 사항이 있나요?
> [FE] Design: 마이페이지, 회원정보 수정 페이지 디자인

- frontend/soltravel/src/components/common/Footer.tsx
- frontend/soltravel/src/pages/MainPage.tsx
- 트래블월렛 삭제, 외화 모임통장으로 수정
- 모임통장 구역 배경색 삭제
- 모임통장 디자인 변경
- 하단 nav바 환전을 모임통장으로 수정
어떤 변경 사항이 있나요?
> [FE] Design: 메인페이지 모임통장 수정, 하단 Nav바 수정

- backend/src/main/java/com/ssafy/soltravel/controller/SettlementController.java
- backend/src/main/java/com/ssafy/soltravel/dto/settlement/SettlementRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
> [BE] Merge: 정산 틀 구현

- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/controller/SettlementController.java
- backend/src/main/java/com/ssafy/soltravel/dto/notification/ExchangeNotificationDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/settlement/SettlementRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/settlement/SettlementResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/service/NotificationService.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- 정산 실행 및 알림 구현
어떤 변경 사항이 있나요?
> [BE] Merge: 정산 실행 및 알림 구현

- backend/src/main/java/com/ssafy/soltravel/service/account_book/AccountBookService.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/ClovaOcrService.java
GPT 요청 메서드 사용
GPT 고정 프롬프트 작성
어떤 변경 사항이 있나요?
> [BE] Feat: OCR 결과 데이터 파싱 기능 구현(GPT)

- backend/src/main/java/com/ssafy/soltravel/controller/UserController.java
회원가입 파라미터 변경(json -> form-data)
어떤 변경 사항이 있나요?
> [BE] Docs: Swagger 파라미터 변경

- frontend/soltravel/src/App.tsx
- frontend/soltravel/src/components/account/MeetingAccount.tsx
- frontend/soltravel/src/components/common/Footer.tsx
- frontend/soltravel/src/pages/account/MeetingAccountList.tsx
- frontend/soltravel/src/redux/accountSlice.ts
- 하단 nav바에 모임통장 navigate 연결
- 모임통장 목록 페이지 디자인
어떤 변경 사항이 있나요?
> [FE] Design: 모임통장 목록 페이지 디자인

- frontend/soltravel/.gitignore
- frontend/soltravel/package-lock.json
- frontend/soltravel/package.json
- frontend/soltravel/src/App.tsx
- frontend/soltravel/src/api/account.ts
- frontend/soltravel/src/components/account/SecurityKeyboard.tsx
- frontend/soltravel/src/components/viewaccount/AccountList.tsx
- frontend/soltravel/src/components/viewaccount/GroupAccount.tsx
- frontend/soltravel/src/lib/axios.ts
- frontend/soltravel/src/pages/account/AccountCreate.tsx
- frontend/soltravel/src/pages/viewaccount/Account.tsx
- frontend/soltravel/src/pages/viewaccount/Detail.tsx
- frontend/soltravel/src/pages/viewaccount/ForeignAccount.tsx
- frontend/soltravel/src/pages/viewaccount/GeneralAccount.tsx
- frontend/soltravel/src/pages/viewaccount/MyAccount.tsx
- frontend/soltravel/src/pages/viewaccount/ViewAccount.tsx
- frontend/soltravel/src/types/account.ts
- /lib/axios : api를 import해서 사용하면 바로 axios 요청 가능
- /types : 백으로 요청해야할 interface type들 정리
- /api : axios요청(이때 /lib/axios.ts를 활용)을 비동기식으로 처리하는 통신들 모음
- 임시로 컴포넌트의 viewaccount를 통해 pages/viewaccount/Viewaccount를 보여줌
- 회원관리 로직 추가
- 임시 보안 키패드 추가
어떤 변경 사항이 있나요?
> [FE] Feat: axios를 활용한 lib, axios, types 컴포넌트 및 보안키패드, 회원관리 구현

- backend/src/main/java/com/ssafy/soltravel/controller/ExchangeController.java
- backend/src/main/java/com/ssafy/soltravel/domain/ExchangeRate.java
- backend/src/main/java/com/ssafy/soltravel/domain/Participant.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeCurrencyDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateRegisterRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRateResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/LatestRateRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/settlement/SettlementRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/repository/ExchangeRateRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- 모임원 계좌로 정산 입금 구현
- currencyCode 변수명 수정
어떤 변경 사항이 있나요?
> [BE] Feat: 모임원 정산 입금 구현

- backend/src/main/java/com/ssafy/soltravel/dto/notification/TransactionNotificationDto.java
- backend/src/main/java/com/ssafy/soltravel/service/NotificationService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
> [BE] Feat: 입출금 알림 구현

- backend/src/main/java/com/ssafy/soltravel/controller/UserController.java
- backend/src/main/java/com/ssafy/soltravel/domain/ExchangeRate.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/EmailValidationResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/service/user/UserService.java
- 이메일 유효성 검사 구현
어떤 변경 사항이 있나요?
> [BE] Feat: 이메일 유효성 검사 구현

- frontend/soltravel/Dockerfile
- frontend/soltravel/default.conf
- frontend/soltravel/src/components/account/AccountDetail.tsx
- frontend/soltravel/src/css/swiper.css
- frontend/soltravel/src/pages/MainPage.tsx
- frontend/soltravel/src/pages/account/MeetingAccountDetail.tsx
- frontend/soltravel/src/types/account.ts
- 일반모임통장 입금, 재환전 버튼 디자인
- 외화모임통장 환전 버튼 디자인
- 모임통장 타입/아이콘 디자인
- 모임통장 참여중인 모임원 표시 디자인
어떤 변경 사항이 있나요?
> [FE] Design: 모임통장 상세 목록 디자인

- backend/src/main/java/com/ssafy/soltravel/config/SecurityConfig.java
- backend/src/main/java/com/ssafy/soltravel/controller/AccountBookController.java
- backend/src/main/java/com/ssafy/soltravel/domain/AccountBookHistory.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/AccountHistodySaveRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/ItemAnalysisDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/ReceiptAnalysisDto.java
- backend/src/main/java/com/ssafy/soltravel/service/GPTService.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/AccountBookService.java
- backend/src/main/resources/db/V1.0_init_data.txt
- backend/src/main/resources/db/V2__C_account_book.sql
OCR 결과 파싱
- OCR 결과 -> 원하는 정보만 추출(String): ChatGPT
- 영수증 String 정보 -> Object : Gson 으로 파싱
- 결과 반환
DB 수정
- account_book 테이블 생성
가계부 저장 기능
- 전체 플로우 & 틀만 작성
어떤 변경 사항이 있나요?
> [BE] Feat: OCR 결과 파싱, DB 수정, 가계부 저장 기능 구현(진행중)

- backend/src/main/resources/db/V3__account_date.sql
- flyway DB 테이블 수정
어떤 변경 사항이 있나요?
> [BE] Build : DB 수정

- backend/src/main/java/com/ssafy/soltravel/domain/AccountBookHistory.java
- backend/src/main/java/com/ssafy/soltravel/domain/ForeignAccount.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/AccountHistodySaveRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/exception/ForeignAccountNotFoundException.java
- backend/src/main/java/com/ssafy/soltravel/mapper/AccountBookMapper.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/AccountBookService.java
- backend/src/main/resources/db/V4__C_cash_history.sql
현금 기록 테이블 생성
Dto 클래스 작성
- AccountHistodySaveRequestDto
엔티티 메서드 구현
- AccountBookHistory: 생성 메서드
- ForeignAccount: 연관관계 편의 메서드
어떤 변경 사항이 있나요?
> [BE] Feat: 가계부 관련 테이블(현금 기록) 생성, Dto, 각종 엔티티 메서드 구현

- backend/src/main/java/com/ssafy/soltravel/domain/CashHistory.java
- backend/src/main/java/com/ssafy/soltravel/domain/Enum/CashTransactionType.java
- backend/src/main/java/com/ssafy/soltravel/domain/ForeignAccount.java
- backend/src/main/java/com/ssafy/soltravel/repository/CashHistoryRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/CashHistoryService.java
CashHistory 엔티티 작성
- CashHistory 엔티티 구현
- CashTransactionType 현금 타입 구현
- ForeignAccount 연관관계 작성
CashHistory 엔티티 관련 메서드 작성
- CashHistory: 현금 출금시 사용하는 생성 메서드 구현
- ForeignAccount 연관관계 편의 메서드 구현
Cash History C, R 구현
- Repository
- C: 엔티티 저장
- R: 단건, 전체 조회, 마지막 로그 조회 구현
- Service
- C: 엔티티 일반 저장, 현금 출금(GET)시 엔티티 저장 기능 구현
어떤 변경 사항이 있나요?
> [BE] Feat: CashHistory C, R 구현

- backend/src/main/java/com/ssafy/soltravel/dto/participants/request/AddParticipantRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- 모임원 추가시 계좌번호 필드 추가
어떤 변경 사항이 있나요?
> [BE] Feat: 모임원 추가시 계좌번호 필드 추가

- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/controller/UserController.java
- backend/src/main/java/com/ssafy/soltravel/domain/CashHistory.java
- backend/src/main/java/com/ssafy/soltravel/dto/account/request/CreateAccountRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/user/EmailValidationDto.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- backend/src/main/java/com/ssafy/soltravel/service/user/UserService.java
- backend/src/main/resources/db/V5__cash_history.sql
- 외화 계좌 출금 기능 구현
- 모임 계좌 생성 시 받은 모임원 자동 초대
어떤 변경 사항이 있나요?
> [BE] Feat : 외화 계좌 출금 및 계좌 생성 시 모임원 초대

- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/AccountInfoDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeCurrencyDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/ForeignTransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/TransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/repository/GeneralAccountRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- 자동 환전 security 보완
- 정산시 외화계좌 잔액 조회 로직 추가
어떤 변경 사항이 있나요?
> [BE] Fix: 자동 환전 security 보완

- backend/src/main/java/com/ssafy/soltravel/controller/TransactionController.java
- backend/src/main/java/com/ssafy/soltravel/dto/exchange/ExchangeRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/settlement/SettlementRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
> [BE] Fix: 정산 출금 로직 분리

- backend/src/main/java/com/ssafy/soltravel/domain/CashHistory.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/ForeignTransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/CashHistoryService.java
- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
> [BE] Fix : 계좌 출금 에러 수정

- backend/src/main/java/com/ssafy/soltravel/dto/account_book/AccountHistorySaveResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/transaction/request/ForeignTransactionRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/AccountBookService.java
가계부 영수증 등록 기능 수정
- 현금 기록 저장 취소
- 출금으로 저장
가계부 조회
- 현금 기록 조회 취소
- 출금만 조회
어떤 변경 사항이 있나요?
> [BE] Feat: 가계부 영수증 등록/ 조회 기능 수정

- backend/src/main/java/com/ssafy/soltravel/controller/ParticipantController.java
- backend/src/main/java/com/ssafy/soltravel/repository/GeneralAccountRepository.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- 특정 유저가 참여한 모든 모임 정보 조회
어떤 변경 사항이 있나요?
> [BE] Feat: 특정 유저가 참여한 모든 모임 정보 조회

- backend/src/main/java/com/ssafy/soltravel/dto/user/EmailValidationDto.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- 이메일 유효성 검사시 사용자 이름 반환되도록 수정
어떤 변경 사항이 있나요?
> [BE] Fix: 이메일 유효성 검사시 사용자 이름 반환되도록 수정

- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- 환전금액 소수점 2자리 되도록 수정
어떤 변경 사항이 있나요?
> [BE] Fix: 환전금액 소수점 2자리 되도록 수정

- backend/src/main/java/com/ssafy/soltravel/controller/AccountBookController.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/AccountHistoryReadRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/AccountHistoryReadResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/DetailAccountHistoryReadRequestDto.java
- backend/src/main/java/com/ssafy/soltravel/dto/account_book/DetailAccountHistoryReadResponseDto.java
- backend/src/main/java/com/ssafy/soltravel/mapper/TransactionMapper.java
- backend/src/main/java/com/ssafy/soltravel/service/account_book/AccountBookService.java
가계부 상세 조회
- Mapper 메서드 구현 (DetailAccountHistoryReadRequestDto -> TransactionHistoryRequestDto)
- 컨트롤러 메서드 구현
- 비즈니스 로직 구현
버그 픽스
- 가계부 조회/ 상세 조회 URL 중복 버그 해결
- 가계부 조회 List 초기화 X 버그 해결
- 가계부 등록 시 출금 api 호출 -> userId 미전달 수정
어떤 변경 사항이 있나요?
> [BE] Feat: 가계부 상세 조회 기능 구현/ 가계부 등록, 조회 버그 픽스

- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- 정산시 모임통장 금액 오류 수정
어떤 변경 사항이 있나요?
> [BE] Fix: 정산시 모임통장 금액 오류 수정

- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- 정산 Transaction 처리
어떤 변경 사항이 있나요?
> [BE] Fix: 정산 Transaction 처리

- backend/src/main/java/com/ssafy/soltravel/service/transaction/TransactionService.java
- 이체 Transaction 처리
어떤 변경 사항이 있나요?
> [BE] Fix: 이체 Transaction 처리

- backend/src/main/resources/db/V7__participant_unique.sql
- DB 수정(Participant 개인 계좌 유니크 제약 삭제)
어떤 변경 사항이 있나요?
> [BE] Build: DB 수정(Participant 개인 계좌 유니크 제약 삭제)

- frontend/soltravel/src/App.tsx
- frontend/soltravel/src/api/transaction.ts
- frontend/soltravel/src/pages/MainPage.tsx
- frontend/soltravel/src/pages/exchange/Exchange.tsx
- frontend/soltravel/src/pages/transaction/Transaction.tsx
- frontend/soltravel/src/pages/user/PrivateRoute.tsx
- frontend/soltravel/src/types/transaction.ts
> [FE] Feat: 이체 기능 구현

- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- backend/src/main/java/com/ssafy/soltravel/service/settlement/SettlementService.java
- 정산 로직 출금 후 입금으로 수정
어떤 변경 사항이 있나요?
> [BE] Fix: 정산 로직 출금 후 입금으로 수정

- frontend/soltravel/src/pages/account/MeetingAccountDetail.tsx
- frontend/soltravel/src/pages/account/MeetingAccountList.tsx
> [FE] Feat: 모임통장 모임원 연결

- backend/src/main/java/com/ssafy/soltravel/controller/ForeignAccountController.java
- backend/src/main/java/com/ssafy/soltravel/service/account/AccountService.java
- 외화 계좌 accountId로 조회 기능 구현
어떤 변경 사항이 있나요?
> [BE] Feat: 외화 계좌 accountId로 조회 기능 구현

- frontend/soltravel/src/components/account/MeetingAccount.tsx
- frontend/soltravel/src/components/mainpage/MainMeetingAccount.tsx
- frontend/soltravel/src/pages/account/MeetingAccountDetail.tsx
아이콘 적용, 디자인 변경, 타입명 출력 기능 구현
어떤 변경 사항이 있나요?
> [FE] Feat: 통장 타입 별 아이콘 출력 기능 구현

- backend/src/main/java/com/ssafy/soltravel/service/exchange/ExchangeService.java
- frontend/soltravel/src/pages/user/Login.tsx
- 환전 금액 예외 버그 처리
- [FE] 로그인시 keyDown 적용
어떤 변경 사항이 있나요?
> [BE] Fix: 환전 금액 예외 버그 처리

- frontend/soltravel/src/api/user.ts
- frontend/soltravel/src/components/user/UserForm.tsx
- frontend/soltravel/src/lib/axios.ts
- frontend/soltravel/src/pages/user/SignUp.tsx
- 회원 가입 시 SMS 인증 구현
어떤 변경 사항이 있나요?
> [FE] Feat: 회원가입 SMS 인증 구현

- frontend/soltravel/src/components/account/inputField/ExchangeRateInput.tsx
- frontend/soltravel/src/pages/account/ForeignMeetingAccountCreate.tsx
환율 입력 칸을 소수점으로 나누기
어떤 변경 사항이 있나요?
> [FE] Feat: 모임 통장 생성 소수점 입력칸 추가

- backend/src/main/java/com/ssafy/soltravel/config/SecurityConfig.java
- 알림 구독 시큐리티 permit 설정
어떤 변경 사항이 있나요?
> [BE] Fix: 알림 구독 시큐리티 permit 설정

- frontend/soltravel/src/api/account.ts
- frontend/soltravel/src/components/account/JoinedMeetingAccount.tsx
- frontend/soltravel/src/components/account/JoinedMeetingAccountDetail.tsx
- frontend/soltravel/src/components/accountBook/DropdownInput.tsx
- frontend/soltravel/src/components/mainpage/MainMeetingAccount.tsx
- frontend/soltravel/src/pages/MainPage.tsx
- frontend/soltravel/src/pages/account/MeetingAccountList.tsx
- frontend/soltravel/src/pages/accountBook/AccountBookDetail.tsx
- frontend/soltravel/src/redux/accountSlice.ts
- 목록에서 내가 모임원인 통장도 보이게 하기 (가입한 것만, 해결 중)
- 메인페이지 입출금 통장 잔액 포맷
- 가계부 선택 버그 해결
- 가계부 캘린더 목록 통신
- 가계부 영수증 인증 통신
어떤 변경 사항이 있나요?
> [FE] Feat: 모임통장 목록 통신 및 가계부 통신

- backend/src/main/java/com/ssafy/soltravel/service/account_book/CashHistoryService.java
- backend/src/main/java/com/ssafy/soltravel/util/DateUtil.java
> [BE] Fix: 가계부 조회 버그 수정

- frontend/soltravel/src/App.tsx
- frontend/soltravel/src/api/account.ts
- frontend/soltravel/src/components/account/AccountDetail.tsx
- frontend/soltravel/src/components/account/JoinedMeetingAccount.tsx
- frontend/soltravel/src/components/account/MeetingAccount.tsx
- frontend/soltravel/src/components/accountBook/AccountBookInputModal.tsx
- frontend/soltravel/src/pages/account/JoinedMeetingAccountDetail.tsx
- frontend/soltravel/src/pages/account/MeetingAccountDetail.tsx
- frontend/soltravel/src/pages/account/MeetingAccountList.tsx
- 목록에서 내가 모임원인 통장도 보이게 하기
- 모임통장 상세페이지 내가 참여한 모임통장의 경우 환전, 재환전 버튼 미출력
어떤 변경 사항이 있나요?
> [FE] Feat: 모임통장 목록 및 상세 목록 통신

- frontend/soltravel/src/pages/MainPage.tsx
- frontend/soltravel/src/pages/account/MeetingAccountList.tsx
- frontend/soltravel/src/pages/user/SignUp.tsx
Test: SSE 테스트 버튼
어떤 변경 사항이 있나요?
> [FE] Test: SSE 테스트 버튼

- frontend/soltravel/src/components/accountBook/AccountBookCalendar.tsx
- frontend/soltravel/src/lib/axios.ts
- frontend/soltravel/src/pages/user/SignUp.tsx
Feat: 회원가입 시 SSE 연결 재설정
어떤 변경 사항이 있나요?
> [FE] Feat: 회원가입 시 SSE 연결 재설정

- backend/src/main/java/com/ssafy/soltravel/domain/GeneralAccount.java
- backend/src/main/java/com/ssafy/soltravel/dto/account/AccountDto.java
- backend/src/main/java/com/ssafy/soltravel/mapper/AccountMapper.java
- backend/src/main/resources/db/V8__general_preference.sql
> [BE] Feat: GeneralAccount에 선호 환율 칼럼 추가

- frontend/soltravel/src/pages/user/MyPage.tsx
마이페이지 백 연동
로그아웃 구현
어떤 변경 사항이 있나요?
> [FE] Feat: 마이페이지 백 연동 + 로그아웃 구현

- frontend/soltravel/src/components/account/AccountDetail.tsx
- frontend/soltravel/src/types/account.ts
> [FE] Feat: 희망 환율 조회 기능 추가

- frontend/soltravel/src/components/accountBook/AccountBookCalendar.tsx
- frontend/soltravel/src/components/accountBook/AccountBookDetailModal.tsx
- frontend/soltravel/src/components/accountBook/AccountBookInputModal.tsx
- frontend/soltravel/src/lib/axios.ts
- frontend/soltravel/src/pages/account/JoinedMeetingAccountDetail.tsx
- frontend/soltravel/src/pages/account/MeetingAccountDetail.tsx
- frontend/soltravel/src/pages/user/SignUp.tsx
- 가계부 상세 내역 디자인 및 통신
어떤 변경 사항이 있나요?
> [FE] Design, Feat: 가계부 상세 내역 디자인 및 통신

- frontend/soltravel/src/components/mainpage/MainMeetingAccount.tsx
- 메인페이지 외환통장 구역 클릭 시에도 모임통장 목록상세로 이동
어떤 변경 사항이 있나요?
> [FE] Fix: 메인페이지 라우팅 수정

- frontend/soltravel/src/components/account/AccountDetail.tsx
- frontend/soltravel/src/components/exchange/ExchangeRate.tsx
- frontend/soltravel/src/components/exchange/ExchangeRateChart.tsx
- frontend/soltravel/src/lib/axios.ts
- frontend/soltravel/src/pages/accountHistory/AccountHistory.tsx
- frontend/soltravel/src/pages/exchange/Exchange.tsx
- frontend/soltravel/src/pages/exchange/ExchangeRate.tsx
- frontend/soltravel/src/pages/settle/Settlement.tsx
- frontend/soltravel/src/pages/transaction/Transaction.tsx
- frontend/soltravel/src/pages/user/Login.tsx
- 정산 페이지 예상 환전 금액이 실제와 다를 수 있음을 고지
- 환전 시 내가 가지고 있는 통장 금액보다 많이 입력하였을 경우 경고 나오게 하기
- 환율 차트 수정
어떤 변경 사항이 있나요?
> [FE] Refactor: 정산 및 환율차트, 환전 페이지 디테일 수정

- frontend/soltravel/src/components/common/Footer.tsx
- frontend/soltravel/src/lib/axios.ts
- frontend/soltravel/src/pages/user/SignUp.tsx
회원가입 시 라우팅 연결 및 SSE 테스트 버튼 삭제
하단 nav바 전체를 환율로 수정
어떤 변경 사항이 있나요?
> [FE] Feat: 하단 nav바 전체를 환율로 수정
